# Generated by Django 4.1.4 on 2022-12-20 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bucket",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("bucket_name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Trashes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("trash_name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bucket"
                    ),
                ),
            ],
        ),
    ]
