version: '3.9'
services:
  web:
      build:
        context: ../
        dockerfile: .docker/Dockerfile
      container_name: recycling-app
      entrypoint: ["/bin/sh", "-c"]
      environment:
        - POSTGRES_USERNAME=${POSTGRES_USERNAME}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - POSTGRES_PORT_INTERNAL=${POSTGRES_PORT_INTERNAL}
        - SECRET_KEY=${SECRET_KEY}
        - DEBUG=${DEBUG}
      command:
        - |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      depends_on:
        recycling-db:
          condition: service_healthy

  recycling-db:
      image: postgres:14
      container_name: recycyling-db
      environment:
        - POSTGRES_USER=${POSTGRES_USERNAME}
        - POSTGRES_DB=${POSTGRES_DATABASE}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
        - "${POSTGRES_PORT}:5432"
      hostname: ${POSTGRES_HOST}
      volumes:
        - ./data/db:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 30s
        retries: 6
      restart: always